### ISSUE TITLE
Rerunning single methods doesn't respect XML parameters

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [cbeust/testng-eclipse#103]
When running a TestNG Test suite from XML you get presented the results of the single @Test decorated methods. When right-clicking one of them and choosing "Run" (like shown in this screenshot http://s22.postimg.org/h0lpgvfap/eclipse_testng.png) the single method is run, but the parameters defined in the XML file are not there anymore.

I found out that the eclipse plugin creates a custom XML Suite ( e.g. /tmp/testng-eclipse--1467718763/testng-customsuite.xml) with default values and the selected method included:

``` xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Default suite">
  <test verbose="2" name="Default test">
    <classes>
      <class name="com.whatever.test.ua.moneyback.MoneyBackGuaranteeTest">
        <methods>
          <include name="testSponsoredModelSecure"/>
        </methods>
      </class>
    </classes>
  </test>
</suite>
```

However, the suite name and all parameters are gone. Since my test class' constructor and some methods have a @Parameters annotation, every try to run a single method fails.

Is there any workaround for this?
I'd already be quite happy with knowing in code what suite is currently running, so I could parse the correct XML file in a data provider myself.

Of course I'd be happy with providing example code in case this issue is not self-explaining.

**Comment by missedone** [comment]
looks like this have been fixed in https://github.com/cbeust/testng/issues/455
I use TestNG 6.9.12 and plugin 6.9.13.201609291640, this works.

the testng-failed.xml was generated by TestNG, and it contains the parameter info, since plugin 6.9.13.201609291640 it respect the param.

feel free to re-open this if the issue remain, and provide more detail info like the testng version, plugin version.
