### ISSUE TITLE
TestNG eclipse plugin in eclipse neon (4.6) not working

### ISSUE THREAD

**Issue by FlowsenAusMonotown** [cbeust/testng-eclipse#262]
### Expected behaviour
Tell us what should happen
Running a test class or method in eclipse with "Run as"
Test runs in eclipse

### Actual behaviour
Tell us what happens instead
Error message: "Reference to undefined variable argLine"

### Steps to reproduce
1. Write a simple test ng test
2. Run with eclipse

### Running Configuration
* Plugin Version: 6.9.11
* (Optional) Plugin Git Revision: 201604020423
  (Since 6.9.11, you can get the plugin git revision via navigating "About Eclipse -> 'Installation Details' at left bottom -> 'Configuration' tab -> scroll down to '*** TestNG for Eclipse Details:' portion ")
* (Optional) Operating System: Mac OS

**Comment by missedone** [comment]
hi @FlowsenAusMonotown 
Not sure if you're aware of the [M2E (Maven eclipse plugin) integration](http://testng.org/doc/eclipse.html#eclipse-m2e-integration) since [6.9.10](https://github.com/cbeust/testng-eclipse/blob/master/CHANGES.md#6910), it parses the configuration section of 'maven-surefire-plugin' or 'maven-failsafe-plugin' in pom.xml, and append the JVM args to the runtime testng process. 

if there're variables in the configuration, it must be visible in the pom.xml so that it can't be correctly substituted.

so, according to your error message, there is var `argLine` might be not defined in pom.xml
please see more detail here: http://testng.org/doc/eclipse.html#eclipse-m2e-integration

PS: you also can [disable the M2E integration](http://testng.org/doc/eclipse.html#eclipse-m2e-integration) as you like.

**Comment by FlowsenAusMonotown** [comment]
hi @missedone 
thx for your reply. This fixes my issue.
