### ISSUE TITLE
Reference to undefined variable env.DOMAIN_PATH

### ISSUE THREAD

**Issue by juherr** [cbeust/testng-eclipse#284]
From http://stackoverflow.com/q/39642358/4234729

**Comment by missedone** [comment]
closed by #286

**Comment by missedone** [comment]
@sujoe

where did you see this error message: 'Reference to undefined variable env.DOMAIN_PATH' ?
do you see anything in the 'Error Log' view (by clicking Window -> Show View -> Other -> Error Log) ?

**Comment by missedone** [comment]
OK, I got the issue, if the you have `env.*` vars in the `systemPropertyVariables`, it was not correct resolve and substituted, now fixed in PR #289 by adding `org.codehaus.plexus.interpolation.EnvarBasedValueSource.EnvarBasedValueSource()`

the fix is available in the latest 6.9.14-SNAPSHOT of TestNG Eclipse Plugin.
refer here for [how to install the beta/snapshot versions](http://testng.org/doc/download.html).

**Comment by missedone** [comment]
here is also one tip if running Eclipse on OS X to correct load system environment variables to Eclipse:[ [1]](http://stackoverflow.com/a/3756674/4867232), [[2]](http://stackoverflow.com/a/12414144/4867232)

in short, if you launch your Eclipse by OS X launchd, you very much like won't see the env vars, to make it work, launch your Eclipse by 'open' on the shell, for example: `open /Applications/eclipse/Eclipse.app`

**Comment by Umesh2Patel** [comment]
I had the similar issue. I was using eclipse neon. After changing to eclipse Kepler the error is gone. It seems eclipse version issue. I suggest you to try changing the eclipse version.

**Comment by missedone** [comment]
@Umesh2Patel
Were you saying you still have issue with latest beta of testng plugin in eclipse neon?

**Comment by Umesh2Patel** [comment]
@missedone 
I could not verify the 6.9.14-SNAPSHOT of TestNG as I was getting some other build error, meantime I change my eclipse version.
